version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "7.4"
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        USER_UID: 1000
        USER_GID: 1000
    environment:
      DATABASE_URL: mysql://root:mariadb@127.0.0.1:3306/app
    command: sleep infinity
    network_mode: service:db
    volumes:
      - ..:/workspace:cached

  db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_DATABASE: app
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
